// This file is auto-generated by TanStack Router

import { createFileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const EditComponentImport = createFileRoute('/edit')()
const AddComponentImport = createFileRoute('/add')()
const IndexComponentImport = createFileRoute('/')()

// Create/Update Routes

const EditComponentRoute = EditComponentImport.update({
  path: '/edit',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/edit.component'),
    'component',
  ),
})

const AddComponentRoute = AddComponentImport.update({
  path: '/add',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/add.component'),
    'component',
  ),
})

const IndexComponentRoute = IndexComponentImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/add': {
      preLoaderRoute: typeof AddComponentImport
      parentRoute: typeof rootRoute
    }
    '/edit': {
      preLoaderRoute: typeof EditComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexComponentRoute,
  AddComponentRoute,
  EditComponentRoute,
])
