// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const EditmilkComponentImport = new FileRoute('/editmilk').createRoute()
const AddmilkComponentImport = new FileRoute('/addmilk').createRoute()
const IndexComponentImport = new FileRoute('/').createRoute()

// Create/Update Routes

const EditmilkComponentRoute = EditmilkComponentImport.update({
  path: '/editmilk',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/editmilk.component'),
    'component',
  ),
})

const AddmilkComponentRoute = AddmilkComponentImport.update({
  path: '/addmilk',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/addmilk.component'),
    'component',
  ),
})

const IndexComponentRoute = IndexComponentImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/addmilk': {
      preLoaderRoute: typeof AddmilkComponentImport
      parentRoute: typeof rootRoute
    }
    '/editmilk': {
      preLoaderRoute: typeof EditmilkComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexComponentRoute,
  AddmilkComponentRoute,
  EditmilkComponentRoute,
])
